# Generated by Django 6.0.4 on 2026-08-03 21:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lista', models.CharField(max_length=120)),
                ('eslogan', models.CharField(max_length=255)),
                ('presidente', models.CharField(max_length=120)),
                ('foto_lista', models.ImageField(blank=True, null=True, upload_to='candidatos/')),
                ('plan_trabajo', models.FileField(upload_to='planes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('color_representativo', models.CharField(blank=True, default='#3B82F6', max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cerrado', 'Cerrado')], default='Aprobada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Elecciones Estudiantiles', max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proceso Electoral',
                'verbose_name_plural': 'Procesos Electorales',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('grado', models.CharField(max_length=30)),
                ('paralelo', models.CharField(max_length=30)),
                ('foto_credencial', models.ImageField(blank=True, null=True, upload_to='estudiantes/')),
                ('ha_votado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash_seguridad', models.CharField(max_length=64, unique=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='elecciones.candidatura')),
            ],
        ),
    ]
