# Generated by Django 6.0.4 on 2026-08-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='cedula',
            new_name='cedula_matricula',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='grado',
            new_name='grado_curso',
        ),
    ]
